/*
 * qnx_master_momentics.c
 *
 * QNX 8.x / Raspberry Pi 4 / Momentics
 *
 * PROJECT:
 *   Dual-CAN vehicle gateway:
 *      CAN0 <-> FRDM-MCXA156 / Node 1
 *      CAN1 <-> FRDM-MCXA236 / Node 2
 *
 * NXP protocol implemented from the supplied MCXA156 source:
 *
 * Node 1:
 *   0x111 Temperature
 *   0x112 Humidity
 *   0x113 Speed
 *   0x114 Battery voltage
 *   0x115 Battery current
 *   0x116 Ultrasonic distance
 *   0x117 IR obstacle
 *   0x201 Node-1 START/STOP command
 *
 * Node 2 branch in the supplied protocol:
 *   0x121..0x125 corresponding normal sensor frames
 *   0x202 Node-2 START/STOP command
 *
 * Broadcast command:
 *   0x200
 *
 * Normal sensor payload:
 *   byte 0..1 = value * 100, big endian
 *   byte 2    = sensor type
 *   byte 3    = node ID
 *   byte 4..7 = reserved
 *
 * IR payload:
 *   byte 0 = 0 clear / 1 obstacle
 *   byte 2 = 0x07
 *   byte 3 = node ID
 *
 * NXP CAN bitrate:
 *   500 kbps
 *
 * NXP sensor period:
 *   500 ms
 *
 * QNX architecture:
 *   CPU0 : Safety + CAN0 TX
 *   CPU1 : CAN0 RX / MCXA156
 *   CPU2 : CAN1 RX / MCXA236
 *   CPU3 : CAN1 TX + Diagnostics
 *
 * RT priority:
 *   P60 Safety preparation
 *   P55 CAN TX schedulers
 *   P50 CAN RX
 *   P15 Diagnostics
 *   P10 Congestion generator
 *   P5  Error archive
 *
 * Memory architecture:
 *   logical data/address/memory banks
 *   fixed-size queues
 *   no per-frame malloc in CAN/SPI path
 *
 * Fault-analysis policy:
 *   WRONG prediction -> historical fixed error ring -> CSV -> gzip
 *   CORRECT prediction -> only latest corrected record
 *
 * NOTE:
 *   Data bus / address bus / memory bus are logical software abstractions
 *   for the architecture presentation. They are not physical Pi CPU buses.
 *
 * Build:
 *   qcc -Wall -Wextra -O2 qnx_master_momentics.c \
 *       -o qnx_master -lsocket -lm
 */

#include <stdio.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <pthread.h>
#include <sched.h>
#include <time.h>
#include <math.h>

#include <sys/types.h>
#include <sys/stat.h>
#include <sys/neutrino.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <devctl.h>
#include <hw/io-spi.h>

/* ========================================================================== */
/* Hardware and network configuration                                         */
/* ========================================================================== */

#define CAN0_DEV                    "/dev/io-spi/spi0/dev0"
#define CAN1_DEV                    "/dev/io-spi/spi0/dev1"

#define CAN_BITRATE                 500000U
#define CAN_APPROX_BITS_8BYTE       111U

#define NODE1_ID                    1U
#define NODE2_ID                    2U

#define NODE1_CMD_ID                0x201U
#define NODE2_CMD_ID                0x202U
#define BROADCAST_CMD_ID            0x200U

#define CMD_STOP                    0x00U
#define CMD_START                   0x01U

#define RX_POLL_US                  500U
#define TX_POLL_US                 100U
#define ARCHIVE_PERIOD_MS           100U

#define SAFETY_DEADLINE_MS          5.0

#define UDP_PORT                    8080
#define UDP_BROADCAST               "169.254.255.255"
#define ID_CONGESTION_NOISE         0x450U

/* Sensor ranges are the ranges generated by the supplied demo firmware. */
#define TEMP_MIN                    24.0f
#define TEMP_MAX                    30.0f
#define HUM_MIN                     45.0f
#define HUM_MAX                     70.0f
#define SPEED_MIN                   20.0f
#define SPEED_MAX                   60.0f
#define VOLT_MIN                    12.0f
#define VOLT_MAX                    14.4f
#define CURR_MIN                    3.0f
#define CURR_MAX                    15.0f

/* Gateway safety policy for demonstration. */
#define ULTRASONIC_STOP_CM          50.0f

/* Fixed memory capacities. */
#define SAFETY_Q_SIZE               64U
#define NORMAL_Q_SIZE               128U
#define NOISE_Q_SIZE                256U
#define ERROR_Q_SIZE                512U
#define ERROR_BATCH_SIZE            32U

#define NOISE_SHED_PERCENT          85U

/* ========================================================================== */
/* MCP2515                                                                     */
/* ========================================================================== */

#define MCP_RESET                   0xC0U
#define MCP_READ                    0x03U
#define MCP_WRITE                   0x02U
#define MCP_BITMOD                  0x05U

#define REG_CANSTAT                 0x0EU
#define REG_CANCTRL                 0x0FU
#define REG_CNF1                    0x2AU
#define REG_CNF2                    0x29U
#define REG_CNF3                    0x28U

#define REG_CANINTF                0x2CU
#define REG_CANINTE                 0x2BU

#define REG_RXB0CTRL                0x60U
#define REG_RXB0SIDH                0x61U
#define REG_RXB1CTRL                0x70U
#define REG_RXB1SIDH                0x71U

#define REG_RXM0SIDH                0x20U
#define REG_RXM0SIDL                0x21U
#define REG_RXM1SIDH                0x24U
#define REG_RXM1SIDL                0x25U

#define REG_TXB0CTRL                0x30U
#define REG_TXB0SIDH                0x31U
#define REG_TXB1CTRL                0x40U
#define REG_TXB1SIDH                0x41U
#define REG_TXB2CTRL                0x50U
#define REG_TXB2SIDH                0x51U

#define MAX_SPI_BYTES               32U

/* ========================================================================== */
/* Sensor definitions                                                         */
/* ========================================================================== */

typedef enum {
    SENSOR_TEMPERATURE = 0,
    SENSOR_HUMIDITY,
    SENSOR_SPEED,
    SENSOR_BATTERY_VOLTAGE,
    SENSOR_BATTERY_CURRENT,
    SENSOR_ULTRASONIC,
    SENSOR_IR,
    SENSOR_COUNT
} sensor_type_t;

typedef struct {
    uint32_t can_id;
    uint8_t dlc;
    uint8_t data[8];

    uint64_t rx_timestamp_ns;

    uint8_t source_bus;
    uint8_t target_bus;
    uint8_t node_id;
    sensor_type_t sensor;
    uint32_t logical_addr;
} gateway_frame_t;

typedef struct {
    bool valid;

    uint8_t node_id;
    sensor_type_t sensor;

    uint32_t can_id;
    uint32_t logical_addr;

    float predicted;
    float actual;
    float error;
    float tolerance;

    uint64_t timestamp_ns;
    uint64_t sequence;
} prediction_record_t;

typedef struct {
    bool valid;

    uint8_t node_id;
    sensor_type_t sensor;

    float value;

    uint32_t can_id;
    uint32_t logical_addr;

    uint64_t timestamp_ns;
} latest_sensor_state_t;

/* ========================================================================== */
/* Fixed queues                                                               */
/* ========================================================================== */

typedef struct {
    gateway_frame_t ring[SAFETY_Q_SIZE];

    uint16_t head;
    uint16_t tail;
    uint16_t count;

    pthread_mutex_t lock;
} safety_queue_t;

typedef struct {
    gateway_frame_t ring[NORMAL_Q_SIZE];

    uint16_t head;
    uint16_t tail;
    uint16_t count;

    pthread_mutex_t lock;
} normal_queue_t;

typedef struct {
    gateway_frame_t ring[NOISE_Q_SIZE];

    uint16_t head;
    uint16_t tail;
    uint16_t count;

    pthread_mutex_t lock;
} noise_queue_t;

typedef struct {
    prediction_record_t ring[ERROR_Q_SIZE];

    uint16_t head;
    uint16_t tail;
    uint16_t count;

    pthread_mutex_t lock;
} error_queue_t;

/* ========================================================================== */
/* Latest correct record                                                     */
/* ========================================================================== */

typedef struct {
    prediction_record_t slot[2];

    unsigned active;

    bool valid;
    bool dirty;

    pthread_mutex_t lock;
} latest_corrected_t;

/* ========================================================================== */
/* Statistics                                                                 */
/* ========================================================================== */

typedef struct {
    pthread_mutex_t lock;

    uint64_t rx_can0;
    uint64_t rx_can1;

    uint64_t tx_can0;
    uint64_t tx_can1;

    uint64_t safety_events;
    uint64_t safety_commands;

    uint64_t normal_forwarded;
    uint64_t noise_forwarded;
    uint64_t noise_dropped;

    uint64_t prediction_total;
    uint64_t prediction_wrong;
    uint64_t prediction_correct;

    uint64_t wrong_archived;
    uint64_t error_overflow;

    uint64_t tx_busy;
    uint64_t tx_failures;

    uint64_t deadline_misses;

    uint64_t safety_latency_sum_ns;
    uint64_t safety_latency_min_ns;
    uint64_t safety_latency_max_ns;

    uint64_t memory_bus_writes;

    uint64_t last_rx_can0;
    uint64_t last_rx_can1;
    uint64_t last_tx_can0;
    uint64_t last_tx_can1;
} gateway_stats_t;

/* ========================================================================== */
/* Globals                                                                    */
/* ========================================================================== */

static volatile sig_atomic_t g_running = 1;
static volatile sig_atomic_t g_congestion = 0;

static int g_can0 = -1;
static int g_can1 = -1;
static int g_udp = -1;

static struct sockaddr_in g_dashboard;

static pthread_t g_th_safety;
static pthread_t g_th_tx0;
static pthread_t g_th_tx1;
static pthread_t g_th_rx0;
static pthread_t g_th_rx1;
static pthread_t g_th_archive;
static pthread_t g_th_noise;
static pthread_t g_th_diag;

static safety_queue_t g_q_safety;
static normal_queue_t g_q_normal;
static noise_queue_t g_q_noise;
static error_queue_t g_q_error;

static latest_corrected_t g_latest_corrected;

static latest_sensor_state_t
    g_latest_state[SENSOR_COUNT];

static gateway_stats_t g_stats;

static pthread_mutex_t g_memory_bus_lock;

static uint64_t g_prediction_sequence = 1U;
static uint64_t g_archive_sequence = 1U;

static unsigned g_cpu_count = 1U;

/*
 * Previous two samples are kept per sensor.
 * Node ID is represented separately in the latest-state table for this
 * simple demonstrator; the same sensor type on Node 2 replaces Node 1 state.
 * Extend to [NODE_COUNT][SENSOR_COUNT] if both nodes need simultaneous
 * historical prediction streams.
 */
static float g_prev_value[SENSOR_COUNT];
static float g_last_value[SENSOR_COUNT];
static bool g_history_valid[SENSOR_COUNT];

static bool g_safety_latched_node1 = false;
static bool g_safety_latched_node2 = false;

/* ========================================================================== */
/* Time utilities                                                             */
/* ========================================================================== */

static uint64_t monotonic_ns(void)
{
    struct timespec ts;

    if (clock_gettime(CLOCK_MONOTONIC,
                      &ts) != 0) {
        return 0U;
    }

    return ((uint64_t)ts.tv_sec *
            1000000000ULL) +
           (uint64_t)ts.tv_nsec;
}

static double ns_to_ms(uint64_t ns)
{
    return (double)ns / 1000000.0;
}

static void signal_handler(int sig)
{
    (void)sig;

    g_running = 0;
}

/* ========================================================================== */
/* QNX processor affinity                                                     */
/* ========================================================================== */

static void pin_current_thread(unsigned cpu)
{
    uint64_t runmask;

    if (g_cpu_count == 0U) {
        return;
    }

    cpu %= g_cpu_count;

    runmask =
        1ULL << cpu;

    /*
     * QNX 8:
     * _NTO_TCTL_RUNMASK uses the uint64_t affinity mask cast as void *.
     */
    if (ThreadCtl(_NTO_TCTL_RUNMASK,
                  (void *)runmask) != 0) {

        fprintf(stderr,
                "[WARN] CPU%u affinity failed: %s\n",
                cpu,
                strerror(errno));
    }
}

/* ========================================================================== */
/* QNX synchronization                                                        */
/* ========================================================================== */

static void init_pi_mutex(pthread_mutex_t *mutex)
{
    pthread_mutexattr_t attr;

    (void)pthread_mutexattr_init(&attr);

    (void)pthread_mutexattr_setprotocol(
        &attr,
        PTHREAD_PRIO_INHERIT);

    (void)pthread_mutex_init(
        mutex,
        &attr);

    (void)pthread_mutexattr_destroy(
        &attr);
}

/* ========================================================================== */
/* Directory setup                                                            */
/* ========================================================================== */

static void mkdir_if_needed(const char *path)
{
    if (mkdir(path, 0777) != 0 &&
        errno != EEXIST) {

        fprintf(stderr,
                "[WARN] mkdir %s: %s\n",
                path,
                strerror(errno));
    }
}

static void init_storage(void)
{
    mkdir_if_needed("/tmp/qnx_master");
    mkdir_if_needed("/tmp/qnx_master/errors");
    mkdir_if_needed("/tmp/qnx_master/errors/archive");
    mkdir_if_needed("/tmp/qnx_master/corrected");
    mkdir_if_needed("/tmp/qnx_master/staging");
}

/* ========================================================================== */
/* Queue functions                                                            */
/* ========================================================================== */

static unsigned safety_size(void)
{
    unsigned count;

    pthread_mutex_lock(&g_q_safety.lock);
    count = g_q_safety.count;
    pthread_mutex_unlock(&g_q_safety.lock);

    return count;
}

static unsigned normal_size(void)
{
    unsigned count;

    pthread_mutex_lock(&g_q_normal.lock);
    count = g_q_normal.count;
    pthread_mutex_unlock(&g_q_normal.lock);

    return count;
}

static unsigned noise_size(void)
{
    unsigned count;

    pthread_mutex_lock(&g_q_noise.lock);
    count = g_q_noise.count;
    pthread_mutex_unlock(&g_q_noise.lock);

    return count;
}

static unsigned error_size(void)
{
    unsigned count;

    pthread_mutex_lock(&g_q_error.lock);
    count = g_q_error.count;
    pthread_mutex_unlock(&g_q_error.lock);

    return count;
}

static bool safety_push(const gateway_frame_t *frame)
{
    bool ok = false;

    pthread_mutex_lock(&g_q_safety.lock);

    if (g_q_safety.count <
        SAFETY_Q_SIZE) {

        gateway_frame_t copy =
            *frame;

        copy.logical_addr =
            0x0800U +
            ((uint32_t)g_q_safety.tail *
             (uint32_t)sizeof(gateway_frame_t));

        g_q_safety.ring[
            g_q_safety.tail] =
            copy;

        g_q_safety.tail =
            (uint16_t)(
                (g_q_safety.tail + 1U) %
                SAFETY_Q_SIZE);

        ++g_q_safety.count;

        ok = true;
    }

    pthread_mutex_unlock(
        &g_q_safety.lock);

    return ok;
}

static bool safety_peek(
    gateway_frame_t *frame)
{
    bool ok = false;

    pthread_mutex_lock(
        &g_q_safety.lock);

    if (g_q_safety.count != 0U) {

        *frame =
            g_q_safety.ring[
                g_q_safety.head];

        ok = true;
    }

    pthread_mutex_unlock(
        &g_q_safety.lock);

    return ok;
}

static bool safety_pop(
    gateway_frame_t *frame)
{
    bool ok = false;

    pthread_mutex_lock(
        &g_q_safety.lock);

    if (g_q_safety.count != 0U) {

        *frame =
            g_q_safety.ring[
                g_q_safety.head];

        g_q_safety.head =
            (uint16_t)(
                (g_q_safety.head + 1U) %
                SAFETY_Q_SIZE);

        --g_q_safety.count;

        ok = true;
    }

    pthread_mutex_unlock(
        &g_q_safety.lock);

    return ok;
}

static bool normal_push(
    const gateway_frame_t *frame)
{
    bool ok = false;

    pthread_mutex_lock(
        &g_q_normal.lock);

    if (g_q_normal.count <
        NORMAL_Q_SIZE) {

        gateway_frame_t copy =
            *frame;

        copy.logical_addr =
            0x2000U +
            ((uint32_t)g_q_normal.tail *
             (uint32_t)sizeof(gateway_frame_t));

        g_q_normal.ring[
            g_q_normal.tail] =
            copy;

        g_q_normal.tail =
            (uint16_t)(
                (g_q_normal.tail + 1U) %
                NORMAL_Q_SIZE);

        ++g_q_normal.count;

        ok = true;
    }

    pthread_mutex_unlock(
        &g_q_normal.lock);

    return ok;
}

static bool normal_peek(
    gateway_frame_t *frame,
    uint8_t target_bus)
{
    bool ok = false;

    pthread_mutex_lock(
        &g_q_normal.lock);

    if (g_q_normal.count != 0U) {

        gateway_frame_t *candidate =
            &g_q_normal.ring[
                g_q_normal.head];

        if (candidate->target_bus ==
            target_bus) {

            *frame = *candidate;
            ok = true;
        }
    }

    pthread_mutex_unlock(
        &g_q_normal.lock);

    return ok;
}

/*
 * The normal queue is one ring shared by both targets.
 * Remove the head only when it belongs to the requested target.
 */
static void normal_drop_target(
    uint8_t target_bus)
{
    uint16_t index;
    uint16_t i;

    pthread_mutex_lock(
        &g_q_normal.lock);

    if (g_q_normal.count == 0U) {
        pthread_mutex_unlock(
            &g_q_normal.lock);
        return;
    }

    if (g_q_normal.ring[
            g_q_normal.head].target_bus ==
        target_bus) {

        g_q_normal.head =
            (uint16_t)(
                (g_q_normal.head + 1U) %
                NORMAL_Q_SIZE);

        --g_q_normal.count;

        pthread_mutex_unlock(
            &g_q_normal.lock);

        return;
    }

    /*
     * If the head belongs to the other CAN bus, search for the first
     * frame for this bus and compact the bounded ring.
     */
    index = g_q_normal.head;

    for (i = 0U;
         i < g_q_normal.count;
         ++i) {

        if (g_q_normal.ring[index].target_bus ==
            target_bus) {

            uint16_t current = index;
            uint16_t previous =
                (uint16_t)(
                    (current +
                     NORMAL_Q_SIZE - 1U) %
                    NORMAL_Q_SIZE);

            while (current !=
                   g_q_normal.head) {

                g_q_normal.ring[current] =
                    g_q_normal.ring[previous];

                current = previous;

                previous =
                    (uint16_t)(
                        (previous +
                         NORMAL_Q_SIZE - 1U) %
                        NORMAL_Q_SIZE);
            }

            g_q_normal.head =
                (uint16_t)(
                    (g_q_normal.head + 1U) %
                    NORMAL_Q_SIZE);

            --g_q_normal.count;

            pthread_mutex_unlock(
                &g_q_normal.lock);

            return;
        }

        index =
            (uint16_t)(
                (index + 1U) %
                NORMAL_Q_SIZE);
    }

    pthread_mutex_unlock(
        &g_q_normal.lock);
}

static bool noise_push(
    const gateway_frame_t *frame)
{
    bool ok = false;

    pthread_mutex_lock(
        &g_q_noise.lock);

    if (g_q_noise.count <
        NOISE_Q_SIZE) {

        gateway_frame_t copy =
            *frame;

        copy.logical_addr =
            0x2500U +
            ((uint32_t)g_q_noise.tail *
             (uint32_t)sizeof(gateway_frame_t));

        g_q_noise.ring[
            g_q_noise.tail] =
            copy;

        g_q_noise.tail =
            (uint16_t)(
                (g_q_noise.tail + 1U) %
                NOISE_Q_SIZE);

        ++g_q_noise.count;

        ok = true;
    }

    pthread_mutex_unlock(
        &g_q_noise.lock);

    return ok;
}

static bool noise_peek(
    gateway_frame_t *frame,
    uint8_t target_bus)
{
    bool ok = false;

    pthread_mutex_lock(
        &g_q_noise.lock);

    if (g_q_noise.count != 0U) {

        gateway_frame_t *candidate =
            &g_q_noise.ring[
                g_q_noise.head];

        if (candidate->target_bus ==
            target_bus) {

            *frame =
                *candidate;

            ok = true;
        }
    }

    pthread_mutex_unlock(
        &g_q_noise.lock);

    return ok;
}

static void noise_drop_target(
    uint8_t target_bus)
{
    uint16_t index;
    uint16_t i;

    pthread_mutex_lock(
        &g_q_noise.lock);

    if (g_q_noise.count == 0U) {
        pthread_mutex_unlock(
            &g_q_noise.lock);
        return;
    }

    if (g_q_noise.ring[
            g_q_noise.head].target_bus ==
        target_bus) {

        g_q_noise.head =
            (uint16_t)(
                (g_q_noise.head + 1U) %
                NOISE_Q_SIZE);

        --g_q_noise.count;

        pthread_mutex_unlock(
            &g_q_noise.lock);

        return;
    }

    index = g_q_noise.head;

    for (i = 0U;
         i < g_q_noise.count;
         ++i) {

        if (g_q_noise.ring[index].target_bus ==
            target_bus) {

            uint16_t current = index;
            uint16_t next =
                (uint16_t)(
                    (current + 1U) %
                    NOISE_Q_SIZE);

            while (current !=
                   g_q_noise.head) {

                g_q_noise.ring[current] =
                    g_q_noise.ring[next];

                current = next;

                next =
                    (uint16_t)(
                        (next + 1U) %
                        NOISE_Q_SIZE);
            }

            g_q_noise.tail =
                (uint16_t)(
                    (g_q_noise.tail +
                     NOISE_Q_SIZE - 1U) %
                    NOISE_Q_SIZE);

            --g_q_noise.count;

            pthread_mutex_unlock(
                &g_q_noise.lock);

            return;
        }

        index =
            (uint16_t)(
                (index + 1U) %
                NOISE_Q_SIZE);
    }

    pthread_mutex_unlock(
        &g_q_noise.lock);
}

static bool error_push(
    const prediction_record_t *record)
{
    bool ok = false;

    pthread_mutex_lock(
        &g_q_error.lock);

    if (g_q_error.count <
        ERROR_Q_SIZE) {

        prediction_record_t copy =
            *record;

        copy.logical_addr =
            0x4000U +
            ((uint32_t)g_q_error.tail *
             (uint32_t)sizeof(prediction_record_t));

        g_q_error.ring[
            g_q_error.tail] =
            copy;

        g_q_error.tail =
            (uint16_t)(
                (g_q_error.tail + 1U) %
                ERROR_Q_SIZE);

        ++g_q_error.count;

        ok = true;
    }

    pthread_mutex_unlock(
        &g_q_error.lock);

    if (!ok) {

        pthread_mutex_lock(
            &g_stats.lock);

        ++g_stats.error_overflow;

        pthread_mutex_unlock(
            &g_stats.lock);
    }

    return ok;
}

static unsigned error_take_batch(
    prediction_record_t *records,
    unsigned maximum)
{
    unsigned count = 0U;

    pthread_mutex_lock(
        &g_q_error.lock);

    while (count < maximum &&
           g_q_error.count != 0U) {

        records[count] =
            g_q_error.ring[
                g_q_error.head];

        g_q_error.head =
            (uint16_t)(
                (g_q_error.head + 1U) %
                ERROR_Q_SIZE);

        --g_q_error.count;

        ++count;
    }

    pthread_mutex_unlock(
        &g_q_error.lock);

    return count;
}

/* ========================================================================== */
/* Latest corrected state                                                     */
/* ========================================================================== */

static void latest_corrected_publish(
    const prediction_record_t *record)
{
    pthread_mutex_lock(
        &g_latest_corrected.lock);

    g_latest_corrected.active ^=
        1U;

    g_latest_corrected.slot[
        g_latest_corrected.active] =
        *record;

    g_latest_corrected.slot[
        g_latest_corrected.active].logical_addr =
        0x5000U;

    g_latest_corrected.valid =
        true;

    g_latest_corrected.dirty =
        true;

    pthread_mutex_unlock(
        &g_latest_corrected.lock);
}

static bool latest_corrected_snapshot(
    prediction_record_t *record)
{
    bool valid;
    bool dirty;

    pthread_mutex_lock(
        &g_latest_corrected.lock);

    valid =
        g_latest_corrected.valid;

    dirty =
        g_latest_corrected.dirty;

    if (valid) {

        *record =
            g_latest_corrected.slot[
                g_latest_corrected.active];
    }

    g_latest_corrected.dirty =
        false;

    pthread_mutex_unlock(
        &g_latest_corrected.lock);

    return valid && dirty;
}

/* ========================================================================== */
/* Sensor mapping                                                             */
/* ========================================================================== */

static const char *sensor_name(
    sensor_type_t sensor)
{
    switch (sensor) {

        case SENSOR_TEMPERATURE:
            return "Temperature";

        case SENSOR_HUMIDITY:
            return "Humidity";

        case SENSOR_SPEED:
            return "Speed";

        case SENSOR_BATTERY_VOLTAGE:
            return "BatteryVoltage";

        case SENSOR_BATTERY_CURRENT:
            return "BatteryCurrent";

        case SENSOR_ULTRASONIC:
            return "Ultrasonic";

        case SENSOR_IR:
            return "IR";

        default:
            return "Unknown";
    }
}

static uint32_t sensor_address(
    uint8_t node_id,
    sensor_type_t sensor)
{
    uint32_t base =
        (node_id == NODE1_ID) ?
            0x1000U :
            0x2000U;

    return base +
           ((uint32_t)sensor * 0x10U);
}

static bool decode_sensor(
    const gateway_frame_t *frame,
    sensor_type_t *sensor,
    float *value,
    uint8_t *node_id)
{
    uint16_t raw;

    if (frame == NULL ||
        sensor == NULL ||
        value == NULL ||
        node_id == NULL ||
        frame->dlc < 4U) {

        return false;
    }

    *node_id =
        frame->data[3];

    switch (frame->can_id) {

        case 0x111U:
        case 0x121U:
            *sensor =
                SENSOR_TEMPERATURE;
            break;

        case 0x112U:
        case 0x122U:
            *sensor =
                SENSOR_HUMIDITY;
            break;

        case 0x113U:
        case 0x123U:
            *sensor =
                SENSOR_SPEED;
            break;

        case 0x114U:
        case 0x124U:
            *sensor =
                SENSOR_BATTERY_VOLTAGE;
            break;

        case 0x115U:
        case 0x125U:
            *sensor =
                SENSOR_BATTERY_CURRENT;
            break;

        case 0x116U:
            *sensor =
                SENSOR_ULTRASONIC;
            break;

        case 0x117U:
            *sensor =
                SENSOR_IR;

            *value =
                frame->data[0] ?
                    1.0f :
                    0.0f;

            return true;

        case 0x126U:
            /*
             * Optional Node-2 ultrasonic extension if the MCXA236
             * firmware is extended using the Node-1 convention.
             */
            *sensor =
                SENSOR_ULTRASONIC;
            break;

        case 0x127U:
            /*
             * Optional Node-2 IR extension.
             */
            *sensor =
                SENSOR_IR;

            *value =
                frame->data[0] ?
                    1.0f :
                    0.0f;

            return true;

        default:
            return false;
    }

    raw =
        ((uint16_t)frame->data[0] << 8) |
        ((uint16_t)frame->data[1]);

    *value =
        (float)raw / 100.0f;

    return true;
}

static float prediction_tolerance(
    sensor_type_t sensor)
{
    switch (sensor) {

        case SENSOR_TEMPERATURE:
            return 0.50f;

        case SENSOR_HUMIDITY:
            return 2.0f;

        case SENSOR_SPEED:
            return 5.0f;

        case SENSOR_BATTERY_VOLTAGE:
            return 0.20f;

        case SENSOR_BATTERY_CURRENT:
            return 0.50f;

        case SENSOR_ULTRASONIC:
            return 15.0f;

        case SENSOR_IR:
            return 0.0f;

        default:
            return 0.0f;
    }
}

static void update_sensor_state(
    uint8_t node_id,
    sensor_type_t sensor,
    float value,
    uint32_t can_id,
    uint64_t timestamp_ns)
{
    latest_sensor_state_t *state;

    (void)node_id;

    state =
        &g_latest_state[sensor];

    state->valid =
        true;

    state->node_id =
        node_id;

    state->sensor =
        sensor;

    state->value =
        value;

    state->can_id =
        can_id;

    state->logical_addr =
        sensor_address(node_id,
                       sensor);

    state->timestamp_ns =
        timestamp_ns;
}

/* ========================================================================== */
/* Prediction engine                                                          */
/* ========================================================================== */

/*
 * Prediction:
 *
 *   predicted[n] =
 *       x[n-1] + (x[n-1] - x[n-2])
 *
 * Actual NXP reading:
 *   reference / correction
 *
 * This is deliberately a lightweight deterministic predictor.
 * The supplied NXP firmware is a sensor publisher, not an AI model.
 */
static void analyze_prediction(
    uint8_t node_id,
    sensor_type_t sensor,
    float actual,
    uint32_t can_id,
    uint64_t timestamp_ns)
{
    float predicted;
    float error_value;
    float tolerance;

    prediction_record_t record;

    if (!g_history_valid[sensor]) {

        g_prev_value[sensor] =
            actual;

        g_last_value[sensor] =
            actual;

        g_history_valid[sensor] =
            true;

        return;
    }

    predicted =
        g_last_value[sensor] +
        (g_last_value[sensor] -
         g_prev_value[sensor]);

    error_value =
        fabsf(actual -
              predicted);

    tolerance =
        prediction_tolerance(sensor);

    record.valid =
        true;

    record.node_id =
        node_id;

    record.sensor =
        sensor;

    record.can_id =
        can_id;

    record.logical_addr =
        sensor_address(node_id,
                       sensor);

    record.predicted =
        predicted;

    record.actual =
        actual;

    record.error =
        error_value;

    record.tolerance =
        tolerance;

    record.timestamp_ns =
        timestamp_ns;

    record.sequence =
        g_prediction_sequence++;

    g_prev_value[sensor] =
        g_last_value[sensor];

    g_last_value[sensor] =
        actual;

    pthread_mutex_lock(
        &g_stats.lock);

    ++g_stats.prediction_total;

    pthread_mutex_unlock(
        &g_stats.lock);

    if (error_value >
        tolerance) {

        /*
         * WRONG:
         * retain the event historically.
         */
        if (error_push(
                &record)) {

            pthread_mutex_lock(
                &g_memory_bus_lock);

            pthread_mutex_lock(
                &g_stats.lock);

            ++g_stats.memory_bus_writes;
            ++g_stats.prediction_wrong;

            pthread_mutex_unlock(
                &g_stats.lock);

            pthread_mutex_unlock(
                &g_memory_bus_lock);
        }

    } else {

        /*
         * CORRECT:
         * overwrite the previous correct state.
         */
        latest_corrected_publish(
            &record);

        pthread_mutex_lock(
            &g_memory_bus_lock);

        pthread_mutex_lock(
            &g_stats.lock);

        ++g_stats.memory_bus_writes;
        ++g_stats.prediction_correct;

        pthread_mutex_unlock(
            &g_stats.lock);

        pthread_mutex_unlock(
            &g_memory_bus_lock);
    }
}

/* ========================================================================== */
/* Safety command generation                                                  */
/* ========================================================================== */

static void request_stop(
    uint8_t node_id,
    uint8_t bus,
    const char *reason,
    uint64_t source_timestamp_ns)
{
    gateway_frame_t command;

    bool *latched =
        (node_id == NODE1_ID) ?
            &g_safety_latched_node1 :
            &g_safety_latched_node2;

    if (*latched) {
        return;
    }

    memset(&command,
           0,
           sizeof(command));

    command.can_id =
        (node_id == NODE1_ID) ?
            NODE1_CMD_ID :
            NODE2_CMD_ID;

    command.dlc =
        8U;

    command.data[0] =
        CMD_STOP;

    command.source_bus =
        bus;

    command.target_bus =
        bus;

    command.node_id =
        node_id;

    command.rx_timestamp_ns =
        source_timestamp_ns;

    command.logical_addr =
        0x0800U;

    if (safety_push(
            &command)) {

        *latched =
            true;

        pthread_mutex_lock(
            &g_stats.lock);

        ++g_stats.safety_events;

        pthread_mutex_unlock(
            &g_stats.lock);

        printf(
            "\n[SAFETY] Node %u STOP: %s\n",
            node_id,
            reason);
    }
}

static void clear_safety_latches(void)
{
    g_safety_latched_node1 =
        false;

    g_safety_latched_node2 =
        false;

    printf(
        "[SAFETY] latches cleared\n");
}

/* ========================================================================== */
/* CAN0 / CAN1 routing                                                        */
/* ========================================================================== */

static void route_sensor_frame(
    gateway_frame_t *frame)
{
    /*
     * A valid sensor frame received from CAN0 is forwarded to CAN1.
     * A valid sensor frame received from CAN1 is forwarded to CAN0.
     *
     * This creates the actual gateway behavior between two NXP CAN domains.
     */
    frame->target_bus =
        (frame->source_bus == 0U) ?
            1U :
            0U;

    if (!normal_push(frame)) {

        pthread_mutex_lock(
            &g_stats.lock);

        ++g_stats.tx_failures;

        pthread_mutex_unlock(
            &g_stats.lock);
    }
}

/* ========================================================================== */
/* MCP2515 SPI                                                                 */
/* ========================================================================== */

typedef union {
    uint64_t alignment;
    uint8_t raw[
        sizeof(spi_xchng_t) +
        MAX_SPI_BYTES];
} spi_buffer_t;

static int spi_xfer(
    int fd,
    const void *tx,
    void *rx,
    size_t length)
{
    spi_buffer_t storage;
    spi_xchng_t *exchange;

    uint32_t total;
    int rc;

    if (length >
        MAX_SPI_BYTES) {

        return EINVAL;
    }

    memset(&storage,
           0,
           sizeof(storage));

    exchange =
        (spi_xchng_t *)storage.raw;

    total =
        (uint32_t)(
            sizeof(spi_xchng_t) +
            length);

    exchange->nbytes =
        (uint32_t)length;

    if (tx != NULL) {

        memcpy(exchange->data,
               tx,
               length);
    }

    rc =
        devctl(fd,
               DCMD_SPI_DATA_XCHNG,
               exchange,
               total,
               NULL);

    if (rc == 0 &&
        rx != NULL) {

        memcpy(rx,
               exchange->data,
               length);
    }

    return rc;
}

static int mcp_write(
    int fd,
    uint8_t reg,
    uint8_t value)
{
    struct __attribute__((packed)) {
        uint8_t cmd;
        uint8_t reg;
        uint8_t value;
    } packet;

    packet.cmd =
        MCP_WRITE;

    packet.reg =
        reg;

    packet.value =
        value;

    return spi_xfer(
        fd,
        &packet,
        NULL,
        sizeof(packet));
}

static int mcp_read(
    int fd,
    uint8_t reg,
    uint8_t *value)
{
    struct __attribute__((packed)) {
        uint8_t cmd;
        uint8_t reg;
        uint8_t dummy;
    } tx;

    struct __attribute__((packed)) {
        uint8_t cmd;
        uint8_t reg;
        uint8_t dummy;
    } rx;

    memset(&tx,
           0,
           sizeof(tx));

    memset(&rx,
           0,
           sizeof(rx));

    tx.cmd =
        MCP_READ;

    tx.reg =
        reg;

    if (spi_xfer(
            fd,
            &tx,
            &rx,
            sizeof(tx)) != 0) {

        return EIO;
    }

    *value =
        rx.dummy;

    return 0;
}

static int mcp_bit_modify(
    int fd,
    uint8_t reg,
    uint8_t mask,
    uint8_t value)
{
    struct __attribute__((packed)) {
        uint8_t cmd;
        uint8_t reg;
        uint8_t mask;
        uint8_t value;
    } packet;

    packet.cmd =
        MCP_BITMOD;

    packet.reg =
        reg;

    packet.mask =
        mask;

    packet.value =
        value;

    return spi_xfer(
        fd,
        &packet,
        NULL,
        sizeof(packet));
}

/* ========================================================================== */
/* CAN initialization                                                        */
/* ========================================================================== */

static int init_can(
    const char *device,
    const char *name)
{
    int fd;
    spi_cfg_t cfg;
    uint8_t status;

    fd =
        open(device,
             O_RDWR);

    if (fd < 0) {

        fprintf(stderr,
                "[-] %s: open failed: %s\n",
                name,
                strerror(errno));

        return -1;
    }

    memset(&cfg,
           0,
           sizeof(cfg));

    cfg.mode =
        8U | (1U << 10);

    cfg.clock_rate =
        5000000U;

    if (devctl(
            fd,
            DCMD_SPI_SET_CONFIG,
            &cfg,
            sizeof(cfg),
            NULL) != 0) {

        fprintf(stderr,
                "[-] %s: SPI config failed\n",
                name);

        close(fd);

        return -1;
    }

    {
        uint8_t reset =
            MCP_RESET;

        if (spi_xfer(
                fd,
                &reset,
                NULL,
                1U) != 0) {

            fprintf(stderr,
                    "[-] %s: MCP reset failed\n",
                    name);

            close(fd);

            return -1;
        }
    }

    usleep(10000);

    /*
     * Existing project assumption:
     * MCP2515 = 16-MHz oscillator.
     * CNF values correspond to the existing 500-kbps project setup.
     */
    (void)mcp_write(
        fd,
        REG_CNF1,
        0x01U);

    (void)mcp_write(
        fd,
        REG_CNF2,
        0x90U);

    (void)mcp_write(
        fd,
        REG_CNF3,
        0x02U);

    /* Accept all standard IDs. */
    (void)mcp_write(
        fd,
        REG_RXM0SIDH,
        0x00U);

    (void)mcp_write(
        fd,
        REG_RXM0SIDL,
        0x00U);

    (void)mcp_write(
        fd,
        REG_RXM1SIDH,
        0x00U);

    (void)mcp_write(
        fd,
        REG_RXM1SIDL,
        0x00U);

    (void)mcp_write(
        fd,
        REG_RXB0CTRL,
        0x64U);

    (void)mcp_write(
        fd,
        REG_RXB1CTRL,
        0x60U);

    (void)mcp_write(
        fd,
        REG_CANINTE,
        0x03U);

    (void)mcp_bit_modify(
        fd,
        REG_CANCTRL,
        0xE0U,
        0x00U);

    status = 0U;

    (void)mcp_read(
        fd,
        REG_CANSTAT,
        &status);

    printf(
        "[+] %s initialized, CANSTAT=0x%02X\n",
        name,
        status);

    return fd;
}

/* ========================================================================== */
/* CAN receive                                                                */
/* ========================================================================== */

static int receive_can(
    int fd,
    uint8_t source_bus,
    gateway_frame_t *frame)
{
    uint8_t intf;
    uint8_t base_reg;

    struct __attribute__((packed)) {
        uint8_t cmd;
        uint8_t reg;
        uint8_t sidh;
        uint8_t sidl;
        uint8_t eid8;
        uint8_t eid0;
        uint8_t dlc;
        uint8_t data[8];
    } tx;

    struct __attribute__((packed)) {
        uint8_t cmd;
        uint8_t reg;
        uint8_t sidh;
        uint8_t sidl;
        uint8_t eid8;
        uint8_t eid0;
        uint8_t dlc;
        uint8_t data[8];
    } rx;

    if (mcp_read(
            fd,
            REG_CANINTF,
            &intf) != 0) {

        return -1;
    }

    if (intf & 0x01U) {

        base_reg =
            REG_RXB0SIDH;

    } else if (intf & 0x02U) {

        base_reg =
            REG_RXB1SIDH;

    } else {

        return 0;
    }

    memset(&tx,
           0,
           sizeof(tx));

    memset(&rx,
           0,
           sizeof(rx));

    tx.cmd =
        MCP_READ;

    tx.reg =
        base_reg;

    if (spi_xfer(
            fd,
            &tx,
            &rx,
            sizeof(tx)) != 0) {

        return -1;
    }

    memset(frame,
           0,
           sizeof(*frame));

    frame->can_id =
        ((uint32_t)rx.sidh << 3) |
        ((uint32_t)rx.sidl >> 5);

    frame->dlc =
        (uint8_t)(
            rx.dlc & 0x0FU);

    if (frame->dlc > 8U) {
        frame->dlc = 8U;
    }

    memcpy(frame->data,
           rx.data,
           frame->dlc);

    frame->rx_timestamp_ns =
        monotonic_ns();

    frame->source_bus =
        source_bus;

    frame->target_bus =
        (source_bus == 0U) ?
            1U :
            0U;

    if (base_reg ==
        REG_RXB0SIDH) {

        (void)mcp_bit_modify(
            fd,
            REG_CANINTF,
            0x01U,
            0x00U);

    } else {

        (void)mcp_bit_modify(
            fd,
            REG_CANINTF,
            0x02U,
            0x00U);
    }

    return 1;
}

/* ========================================================================== */
/* CAN transmit                                                               */
/* ========================================================================== */

static int tx_buffer(
    int fd,
    unsigned buffer,
    const gateway_frame_t *frame)
{
    uint8_t ctrl_reg;
    uint8_t data_reg;
    uint8_t tx_value;
    uint8_t ctrl;

    struct __attribute__((packed)) {
        uint8_t cmd;
        uint8_t reg;
        uint8_t sidh;
        uint8_t sidl;
        uint8_t eid8;
        uint8_t eid0;
        uint8_t dlc;
        uint8_t data[8];
    } packet;

    if (frame == NULL ||
        frame->dlc > 8U ||
        buffer > 2U) {

        return EINVAL;
    }

    if (buffer == 0U) {

        ctrl_reg =
            REG_TXB0CTRL;

        data_reg =
            REG_TXB0SIDH;

        tx_value =
            0x0BU;

    } else if (buffer == 1U) {

        ctrl_reg =
            REG_TXB1CTRL;

        data_reg =
            REG_TXB1SIDH;

        tx_value =
            0x0AU;

    } else {

        ctrl_reg =
            REG_TXB2CTRL;

        data_reg =
            REG_TXB2SIDH;

        tx_value =
            0x08U;
    }

    if (mcp_read(
            fd,
            ctrl_reg,
            &ctrl) != 0) {

        return EIO;
    }

    if (ctrl & 0x08U) {
        return EBUSY;
    }

    memset(&packet,
           0,
           sizeof(packet));

    packet.cmd =
        MCP_WRITE;

    packet.reg =
        data_reg;

    packet.sidh =
        (uint8_t)(
            frame->can_id >> 3);

    packet.sidl =
        (uint8_t)(
            frame->can_id << 5);

    packet.dlc =
        frame->dlc;

    memcpy(packet.data,
           frame->data,
           frame->dlc);

    if (spi_xfer(
            fd,
            &packet,
            NULL,
            7U + frame->dlc) != 0) {

        return EIO;
    }

    return mcp_write(
        fd,
        ctrl_reg,
        tx_value);
}

/* ========================================================================== */
/* THREAD: CAN0 RX                                                            */
/* ========================================================================== */

static void *can0_rx_thread(void *arg)
{
    (void)arg;

    pin_current_thread(1U);

    while (g_running) {

        gateway_frame_t frame;

        int rc =
            receive_can(
                g_can0,
                0U,
                &frame);

        if (rc <= 0) {

            usleep(RX_POLL_US);

            continue;
        }

        pthread_mutex_lock(
            &g_stats.lock);

        ++g_stats.rx_can0;

        pthread_mutex_unlock(
            &g_stats.lock);

        {
            sensor_type_t sensor;
            float value;
            uint8_t node_id;

            if (!decode_sensor(
                    &frame,
                    &sensor,
                    &value,
                    &node_id)) {

                /*
                 * Non-sensor CAN0 frames are still forwarded as
                 * low/normal traffic.
                 */
                frame.node_id = NODE1_ID;

                if (frame.can_id ==
                    NODE1_CMD_ID ||
                    frame.can_id ==
                    BROADCAST_CMD_ID) {

                    continue;
                }

                if (!normal_push(
                        &frame)) {

                    pthread_mutex_lock(
                        &g_stats.lock);

                    ++g_stats.tx_failures;

                    pthread_mutex_unlock(
                        &g_stats.lock);
                }

                continue;
            }

            frame.node_id =
                node_id;

            frame.sensor =
                sensor;

            frame.logical_addr =
                sensor_address(
                    node_id,
                    sensor);

            update_sensor_state(
                node_id,
                sensor,
                value,
                frame.can_id,
                frame.rx_timestamp_ns);

            analyze_prediction(
                node_id,
                sensor,
                value,
                frame.can_id,
                frame.rx_timestamp_ns);

            /*
             * Real safety sensors from Node 1.
             */
            if (sensor ==
                SENSOR_ULTRASONIC) {

                if (value > 0.0f &&
                    value <=
                    ULTRASONIC_STOP_CM) {

                    request_stop(
                        node_id,
                        0U,
                        "Node 1 ultrasonic distance <= safety threshold",
                        frame.rx_timestamp_ns);
                }

            } else if (sensor ==
                       SENSOR_IR) {

                if (value > 0.5f) {

                    request_stop(
                        node_id,
                        0U,
                        "Node 1 IR obstacle",
                        frame.rx_timestamp_ns);
                }
            }

            route_sensor_frame(
                &frame);
        }
    }

    return NULL;
}

/* ========================================================================== */
/* THREAD: CAN1 RX                                                            */
/* ========================================================================== */

static void *can1_rx_thread(void *arg)
{
    (void)arg;

    pin_current_thread(2U);

    while (g_running) {

        gateway_frame_t frame;

        int rc =
            receive_can(
                g_can1,
                1U,
                &frame);

        if (rc <= 0) {

            usleep(RX_POLL_US);

            continue;
        }

        pthread_mutex_lock(
            &g_stats.lock);

        ++g_stats.rx_can1;

        pthread_mutex_unlock(
            &g_stats.lock);

        {
            sensor_type_t sensor;
            float value;
            uint8_t node_id;

            if (!decode_sensor(
                    &frame,
                    &sensor,
                    &value,
                    &node_id)) {

                if (!normal_push(
                        &frame)) {

                    pthread_mutex_lock(
                        &g_stats.lock);

                    ++g_stats.tx_failures;

                    pthread_mutex_unlock(
                        &g_stats.lock);
                }

                continue;
            }

            frame.node_id =
                node_id;

            frame.sensor =
                sensor;

            frame.logical_addr =
                sensor_address(
                    node_id,
                    sensor);

            update_sensor_state(
                node_id,
                sensor,
                value,
                frame.can_id,
                frame.rx_timestamp_ns);

            analyze_prediction(
                node_id,
                sensor,
                value,
                frame.can_id,
                frame.rx_timestamp_ns);

            /*
             * These rules are available for optional Node-2 ultrasonic/IR
             * extensions. The supplied MCXA156 file establishes 0x116/0x117
             * on Node 1; the 0x126/0x127 cases above are gateway extensions
             * and must match your actual MCXA236 code before use.
             */
            if (sensor ==
                SENSOR_ULTRASONIC &&
                value > 0.0f &&
                value <=
                ULTRASONIC_STOP_CM) {

                request_stop(
                    node_id,
                    1U,
                    "Node 2 ultrasonic distance <= safety threshold",
                    frame.rx_timestamp_ns);

            } else if (
                sensor ==
                SENSOR_IR &&
                value > 0.5f) {

                request_stop(
                    node_id,
                    1U,
                    "Node 2 IR obstacle",
                    frame.rx_timestamp_ns);
            }

            route_sensor_frame(
                &frame);
        }
    }

    return NULL;
}

/* ========================================================================== */
/* THREAD: Safety task P60                                                    */
/* ========================================================================== */

static void *safety_thread(void *arg)
{
    (void)arg;

    pin_current_thread(0U);

    /*
     * Highest-priority safety monitor. It checks the already-decoded
     * Node-1 safety sensors. The CAN RX path also performs the immediate
     * check, while this task provides an independent safety-monitoring layer.
     *
     * No file I/O, gzip, dynamic allocation, or dashboard work occurs here.
     */
    while (g_running) {

        if (g_latest_state[SENSOR_ULTRASONIC].valid &&
            g_latest_state[SENSOR_ULTRASONIC].node_id == NODE1_ID &&
            g_latest_state[SENSOR_ULTRASONIC].value > 0.0f &&
            g_latest_state[SENSOR_ULTRASONIC].value <= ULTRASONIC_STOP_CM) {

            request_stop(
                NODE1_ID,
                0U,
                "P60 monitor: ultrasonic threshold",
                g_latest_state[SENSOR_ULTRASONIC].timestamp_ns);
        }

        if (g_latest_state[SENSOR_IR].valid &&
            g_latest_state[SENSOR_IR].node_id == NODE1_ID &&
            g_latest_state[SENSOR_IR].value > 0.5f) {

            request_stop(
                NODE1_ID,
                0U,
                "P60 monitor: IR obstacle",
                g_latest_state[SENSOR_IR].timestamp_ns);
        }

        /* Periodic 1-ms safety monitor; it must sleep to avoid starving P55. */
        usleep(1000U);
    }

    return NULL;
}

/* ========================================================================== */
/* THREAD: CAN0 TX scheduler P55                                              */
/* ========================================================================== */

static void *can0_tx_thread(void *arg)
{
    (void)arg;

    pin_current_thread(0U);

    while (g_running) {

        gateway_frame_t frame;

        /*
         * SAFETY FIRST on CAN0.
         */
        if (safety_peek(
                &frame)) {

            if (frame.target_bus ==
                0U) {

                int rc =
                    tx_buffer(
                        g_can0,
                        0U,
                        &frame);

                if (rc == 0) {

                    uint64_t latency =
                        monotonic_ns() -
                        frame.rx_timestamp_ns;

                    (void)safety_pop(
                        &frame);

                    pthread_mutex_lock(
                        &g_stats.lock);

                    ++g_stats.tx_can0;
                    ++g_stats.safety_commands;

                    g_stats.safety_latency_sum_ns +=
                        latency;

                    if (g_stats.safety_latency_min_ns ==
                        UINT64_MAX ||
                        latency <
                        g_stats.safety_latency_min_ns) {

                        g_stats.safety_latency_min_ns =
                            latency;
                    }

                    if (latency >
                        g_stats.safety_latency_max_ns) {

                        g_stats.safety_latency_max_ns =
                            latency;
                    }

                    if (ns_to_ms(latency) >
                        SAFETY_DEADLINE_MS) {

                        ++g_stats.deadline_misses;
                    }

                    pthread_mutex_unlock(
                        &g_stats.lock);

                    continue;

                } else if (rc == EBUSY) {

                    pthread_mutex_lock(
                        &g_stats.lock);

                    ++g_stats.tx_busy;

                    pthread_mutex_unlock(
                        &g_stats.lock);

                } else {

                    pthread_mutex_lock(
                        &g_stats.lock);

                    ++g_stats.tx_failures;

                    pthread_mutex_unlock(
                        &g_stats.lock);
                }
            }
        }

        /*
         * NORMAL routed traffic.
         */
        if (normal_peek(
                &frame,
                0U)) {

            int rc =
                tx_buffer(
                    g_can0,
                    1U,
                    &frame);

            if (rc == 0) {

                normal_drop_target(
                    0U);

                pthread_mutex_lock(
                    &g_stats.lock);

                ++g_stats.tx_can0;
                ++g_stats.normal_forwarded;

                pthread_mutex_unlock(
                    &g_stats.lock);

                continue;
            }
        }

        /*
         * LOW-priority noise.
         */
        if (noise_peek(
                &frame,
                0U)) {

            int rc =
                tx_buffer(
                    g_can0,
                    2U,
                    &frame);

            if (rc == 0) {

                noise_drop_target(
                    0U);

                pthread_mutex_lock(
                    &g_stats.lock);

                ++g_stats.tx_can0;
                ++g_stats.noise_forwarded;

                pthread_mutex_unlock(
                    &g_stats.lock);

                continue;
            }
        }

        usleep(TX_POLL_US);
    }

    return NULL;
}

/* ========================================================================== */
/* THREAD: CAN1 TX scheduler P55                                              */
/* ========================================================================== */

static void *can1_tx_thread(void *arg)
{
    (void)arg;

    pin_current_thread(3U);

    while (g_running) {

        gateway_frame_t frame;

        /*
         * SAFETY FIRST on CAN1.
         */
        if (safety_peek(
                &frame)) {

            if (frame.target_bus ==
                1U) {

                int rc =
                    tx_buffer(
                        g_can1,
                        0U,
                        &frame);

                if (rc == 0) {

                    uint64_t latency =
                        monotonic_ns() -
                        frame.rx_timestamp_ns;

                    (void)safety_pop(
                        &frame);

                    pthread_mutex_lock(
                        &g_stats.lock);

                    ++g_stats.tx_can1;
                    ++g_stats.safety_commands;

                    g_stats.safety_latency_sum_ns +=
                        latency;

                    if (g_stats.safety_latency_min_ns ==
                        UINT64_MAX ||
                        latency <
                        g_stats.safety_latency_min_ns) {

                        g_stats.safety_latency_min_ns =
                            latency;
                    }

                    if (latency >
                        g_stats.safety_latency_max_ns) {

                        g_stats.safety_latency_max_ns =
                            latency;
                    }

                    if (ns_to_ms(latency) >
                        SAFETY_DEADLINE_MS) {

                        ++g_stats.deadline_misses;
                    }

                    pthread_mutex_unlock(
                        &g_stats.lock);

                    continue;

                } else if (rc == EBUSY) {

                    pthread_mutex_lock(
                        &g_stats.lock);

                    ++g_stats.tx_busy;

                    pthread_mutex_unlock(
                        &g_stats.lock);

                } else {

                    pthread_mutex_lock(
                        &g_stats.lock);

                    ++g_stats.tx_failures;

                    pthread_mutex_unlock(
                        &g_stats.lock);
                }
            }
        }

        /*
         * NORMAL routed traffic.
         */
        if (normal_peek(
                &frame,
                1U)) {

            int rc =
                tx_buffer(
                    g_can1,
                    1U,
                    &frame);

            if (rc == 0) {

                normal_drop_target(
                    1U);

                pthread_mutex_lock(
                    &g_stats.lock);

                ++g_stats.tx_can1;
                ++g_stats.normal_forwarded;

                pthread_mutex_unlock(
                    &g_stats.lock);

                continue;
            }
        }

        /*
         * LOW-priority noise.
         */
        if (noise_peek(
                &frame,
                1U)) {

            int rc =
                tx_buffer(
                    g_can1,
                    2U,
                    &frame);

            if (rc == 0) {

                noise_drop_target(
                    1U);

                pthread_mutex_lock(
                    &g_stats.lock);

                ++g_stats.tx_can1;
                ++g_stats.noise_forwarded;

                pthread_mutex_unlock(
                    &g_stats.lock);

                continue;
            }
        }

        usleep(TX_POLL_US);
    }

    return NULL;
}

/* ========================================================================== */
/* THREAD: congestion generator P10                                           */
/* ========================================================================== */

static void *noise_thread(void *arg)
{
    (void)arg;

    pin_current_thread(2U);

    while (g_running) {

        if (!g_congestion) {

            usleep(1000U);

            continue;
        }

        /*
         * Produce noise on both CAN domains so load-shedding is visible
         * independently on both network sides.
         */
        {
            gateway_frame_t frame0;
            gateway_frame_t frame1;

            memset(&frame0,
                   0,
                   sizeof(frame0));

            frame0.can_id =
                ID_CONGESTION_NOISE;

            frame0.dlc =
                8U;

            frame0.source_bus =
                0U;

            frame0.target_bus =
                1U;

            frame0.rx_timestamp_ns =
                monotonic_ns();

            frame0.data[0] =
                0xA5U;

            frame0.data[1] =
                0x5AU;

            memset(&frame1,
                   0,
                   sizeof(frame1));

            frame1.can_id =
                ID_CONGESTION_NOISE;

            frame1.dlc =
                8U;

            frame1.source_bus =
                1U;

            frame1.target_bus =
                0U;

            frame1.rx_timestamp_ns =
                monotonic_ns();

            frame1.data[0] =
                0x5AU;

            frame1.data[1] =
                0xA5U;

            if (noise_size() >=
                (NOISE_Q_SIZE *
                 NOISE_SHED_PERCENT) /
                100U) {

                pthread_mutex_lock(
                    &g_stats.lock);

                g_stats.noise_dropped +=
                    2U;

                pthread_mutex_unlock(
                    &g_stats.lock);

            } else {

                (void)noise_push(
                    &frame0);

                (void)noise_push(
                    &frame1);
            }
        }

        usleep(100U);
    }

    return NULL;
}

/* ========================================================================== */
/* Error archival                                                             */
/* ========================================================================== */

static bool gzip_available(void)
{
    return access(
               "/usr/bin/gzip",
               X_OK) == 0 ||
           access(
               "/bin/gzip",
               X_OK) == 0;
}

static int write_all(
    int fd,
    const char *data,
    size_t length)
{
    size_t offset = 0U;

    while (offset <
           length) {

        ssize_t n =
            write(
                fd,
                data + offset,
                length - offset);

        if (n < 0) {

            if (errno ==
                EINTR) {

                continue;
            }

            return -1;
        }

        offset +=
            (size_t)n;
    }

    return 0;
}

static void gzip_file(
    const char *path)
{
    char command[512];

    if (!gzip_available()) {
        return;
    }

    if (access(
            "/usr/bin/gzip",
            X_OK) == 0) {

        (void)snprintf(
            command,
            sizeof(command),
            "/usr/bin/gzip -f \"%s\"",
            path);

    } else {

        (void)snprintf(
            command,
            sizeof(command),
            "/bin/gzip -f \"%s\"",
            path);
    }

    /*
     * IMPORTANT:
     * Called ONLY by P5 archive thread.
     */
    (void)system(command);
}

static void archive_batch(
    prediction_record_t *records,
    unsigned count)
{
    char raw_path[256];
    char gz_path[256];
    char final_path[256];

    int fd;

    unsigned i;

    if (count == 0U) {
        return;
    }

    (void)snprintf(
        raw_path,
        sizeof(raw_path),
        "/tmp/qnx_master/staging/"
        "error_batch_%06llu.csv",
        (unsigned long long)
            g_archive_sequence);

    fd =
        open(raw_path,
             O_WRONLY |
             O_CREAT |
             O_TRUNC,
             0666);

    if (fd < 0) {
        return;
    }

    {
        static const char header[] =
            "seq,node_id,can_id,logical_address,"
            "sensor,predicted,actual,error,tolerance,"
            "timestamp_ns\n";

        (void)write_all(
            fd,
            header,
            strlen(header));
    }

    for (i = 0U;
         i < count;
         ++i) {

        char line[512];

        (void)snprintf(
            line,
            sizeof(line),
            "%llu,%u,0x%03X,0x%08X,%s,"
            "%.3f,%.3f,%.3f,%.3f,%llu\n",

            (unsigned long long)
                records[i].sequence,

            records[i].node_id,

            records[i].can_id,

            records[i].logical_addr,

            sensor_name(
                records[i].sensor),

            records[i].predicted,

            records[i].actual,

            records[i].error,

            records[i].tolerance,

            (unsigned long long)
                records[i].timestamp_ns);

        (void)write_all(
            fd,
            line,
            strlen(line));
    }

    (void)fsync(fd);

    close(fd);

    gzip_file(raw_path);

    (void)snprintf(
        gz_path,
        sizeof(gz_path),
        "%s.gz",
        raw_path);

    if (access(
            gz_path,
            F_OK) == 0) {

        (void)snprintf(
            final_path,
            sizeof(final_path),
            "/tmp/qnx_master/errors/archive/"
            "error_batch_%06llu.csv.gz",
            (unsigned long long)
                g_archive_sequence);

        (void)rename(
            gz_path,
            final_path);

    } else {

        (void)snprintf(
            final_path,
            sizeof(final_path),
            "/tmp/qnx_master/errors/archive/"
            "error_batch_%06llu.csv",
            (unsigned long long)
                g_archive_sequence);

        (void)rename(
            raw_path,
            final_path);
    }

    pthread_mutex_lock(
        &g_stats.lock);

    g_stats.wrong_archived +=
        count;

    pthread_mutex_unlock(
        &g_stats.lock);

    ++g_archive_sequence;
}

static void write_latest_corrected(
    const prediction_record_t *record)
{
    char tmp_path[256];
    char final_path[256];
    char json[1024];

    int fd;

    (void)snprintf(
        tmp_path,
        sizeof(tmp_path),
        "/tmp/qnx_master/corrected/"
        "latest.tmp");

    (void)snprintf(
        final_path,
        sizeof(final_path),
        "/tmp/qnx_master/corrected/"
        "latest_corrected.json");

    fd =
        open(tmp_path,
             O_WRONLY |
             O_CREAT |
             O_TRUNC,
             0666);

    if (fd < 0) {
        return;
    }

    (void)snprintf(
        json,
        sizeof(json),

        "{\n"
        "  \"sequence\": %llu,\n"
        "  \"node_id\": %u,\n"
        "  \"sensor\": \"%s\",\n"
        "  \"can_id\": \"0x%03X\",\n"
        "  \"logical_address\": \"0x%08X\",\n"
        "  \"predicted\": %.3f,\n"
        "  \"actual\": %.3f,\n"
        "  \"difference\": %.3f,\n"
        "  \"tolerance\": %.3f,\n"
        "  \"timestamp_ns\": %llu\n"
        "}\n",

        (unsigned long long)
            record->sequence,

        record->node_id,

        sensor_name(
            record->sensor),

        record->can_id,

        record->logical_addr,

        record->predicted,

        record->actual,

        record->error,

        record->tolerance,

        (unsigned long long)
            record->timestamp_ns);

    (void)write_all(
        fd,
        json,
        strlen(json));

    (void)fsync(fd);

    close(fd);

    (void)rename(
        tmp_path,
        final_path);
}

/* ========================================================================== */
/* THREAD: archive P5                                                         */
/* ========================================================================== */

static void *archive_thread(void *arg)
{
    (void)arg;

    pin_current_thread(3U);

    while (g_running ||
           error_size() != 0U) {

        prediction_record_t batch[
            ERROR_BATCH_SIZE];

        unsigned count =
            error_take_batch(
                batch,
                ERROR_BATCH_SIZE);

        /*
         * ERROR FIRST.
         */
        if (count != 0U) {

            archive_batch(
                batch,
                count);

            continue;
        }

        /*
         * Correct records are only a current snapshot.
         */
        {
            prediction_record_t latest;

            if (latest_corrected_snapshot(
                    &latest)) {

                write_latest_corrected(
                    &latest);
            }
        }

        usleep(
            ARCHIVE_PERIOD_MS *
            1000U);
    }

    return NULL;
}

/* ========================================================================== */
/* THREAD: diagnostics P15                                                    */
/* ========================================================================== */

static double thread_cpu_percent(
    pthread_t thread,
    uint64_t *last_cpu_ns,
    uint64_t wall_delta_ns)
{
    clockid_t clock_id;
    struct timespec ts;

    uint64_t current_cpu_ns;
    uint64_t delta_cpu_ns;

    if (pthread_getcpuclockid(
            thread,
            &clock_id) != 0) {

        return 0.0;
    }

    if (clock_gettime(
            clock_id,
            &ts) != 0) {

        return 0.0;
    }

    current_cpu_ns =
        ((uint64_t)ts.tv_sec *
         1000000000ULL) +
        (uint64_t)ts.tv_nsec;

    if (*last_cpu_ns == 0U) {

        *last_cpu_ns =
            current_cpu_ns;

        return 0.0;
    }

    delta_cpu_ns =
        current_cpu_ns -
        *last_cpu_ns;

    *last_cpu_ns =
        current_cpu_ns;

    if (wall_delta_ns == 0U) {
        return 0.0;
    }

    {
        double percentage =
            ((double)delta_cpu_ns /
             (double)wall_delta_ns) *
            100.0;

        if (percentage < 0.0) {
            percentage = 0.0;
        }

        if (percentage > 100.0) {
            percentage = 100.0;
        }

        return percentage;
    }
}

static void *diagnostics_thread(
    void *arg)
{
    (void)arg;

    uint64_t last_wall_ns =
        monotonic_ns();

    uint64_t c_safety = 0U;
    uint64_t c_tx0 = 0U;
    uint64_t c_tx1 = 0U;
    uint64_t c_rx0 = 0U;
    uint64_t c_rx1 = 0U;
    uint64_t c_archive = 0U;
    uint64_t c_noise = 0U;
    uint64_t c_diag = 0U;

    pin_current_thread(3U);

    while (g_running) {

        uint64_t wall_now;
        uint64_t wall_delta;

        uint64_t rx0;
        uint64_t rx1;
        uint64_t tx0;
        uint64_t tx1;

        uint64_t safety_sum;
        uint64_t safety_min;
        uint64_t safety_max;
        uint64_t safety_count;

        uint64_t deadline_misses;
        uint64_t wrong;
        uint64_t correct;
        uint64_t archived;
        uint64_t overflow;

        unsigned qs;
        unsigned qn;
        unsigned qnoise;
        unsigned qerror;

        double cpu0;
        double cpu1;
        double cpu2;
        double cpu3;

        double rx_fps;
        double tx_fps;
        double busload;

        double avg_latency;
        double jitter;

        sleep(1);

        wall_now =
            monotonic_ns();

        wall_delta =
            wall_now -
            last_wall_ns;

        cpu0 =
            thread_cpu_percent(
                g_th_safety,
                &c_safety,
                wall_delta);

        cpu0 +=
            thread_cpu_percent(
                g_th_tx0,
                &c_tx0,
                wall_delta);

        cpu1 =
            thread_cpu_percent(
                g_th_rx0,
                &c_rx0,
                wall_delta);

        cpu2 =
            thread_cpu_percent(
                g_th_rx1,
                &c_rx1,
                wall_delta);

        cpu3 =
            thread_cpu_percent(
                g_th_tx1,
                &c_tx1,
                wall_delta);

        cpu3 +=
            thread_cpu_percent(
                g_th_diag,
                &c_diag,
                wall_delta);

        /*
         * Archive and noise are both CPU2/CPU3 depending on CPU availability.
         * They are separately measured below and displayed as diagnostic
         * application load.
         */
        {
            double archive_cpu =
                thread_cpu_percent(
                    g_th_archive,
                    &c_archive,
                    wall_delta);

            double noise_cpu =
                thread_cpu_percent(
                    g_th_noise,
                    &c_noise,
                    wall_delta);

            cpu2 +=
                archive_cpu;

            cpu3 +=
                noise_cpu;
        }

        pthread_mutex_lock(
            &g_stats.lock);

        rx0 =
            g_stats.rx_can0;

        rx1 =
            g_stats.rx_can1;

        tx0 =
            g_stats.tx_can0;

        tx1 =
            g_stats.tx_can1;

        safety_sum =
            g_stats.safety_latency_sum_ns;

        safety_min =
            g_stats.safety_latency_min_ns;

        safety_max =
            g_stats.safety_latency_max_ns;

        safety_count =
            g_stats.safety_commands;

        deadline_misses =
            g_stats.deadline_misses;

        wrong =
            g_stats.prediction_wrong;

        correct =
            g_stats.prediction_correct;

        archived =
            g_stats.wrong_archived;

        overflow =
            g_stats.error_overflow;

        pthread_mutex_unlock(
            &g_stats.lock);

        qs =
            safety_size();

        qn =
            normal_size();

        qnoise =
            noise_size();

        qerror =
            error_size();

        rx_fps =
            (double)(
                (rx0 - g_stats.last_rx_can0) +
                (rx1 - g_stats.last_rx_can1));

        tx_fps =
            (double)(
                (tx0 - g_stats.last_tx_can0) +
                (tx1 - g_stats.last_tx_can1));

        busload =
            ((rx_fps + tx_fps) *
             (double)CAN_APPROX_BITS_8BYTE *
             100.0) /
            (double)CAN_BITRATE;

        if (busload > 100.0) {
            busload = 100.0;
        }

        avg_latency = 0.0;

        if (safety_count != 0U) {

            avg_latency =
                ns_to_ms(
                    safety_sum /
                    safety_count);
        }

        if (safety_min ==
                UINT64_MAX ||
            safety_max <
                safety_min) {

            jitter = 0.0;

        } else {

            jitter =
                ns_to_ms(
                    safety_max -
                    safety_min);
        }

        if (cpu0 > 100.0) cpu0 = 100.0;
        if (cpu1 > 100.0) cpu1 = 100.0;
        if (cpu2 > 100.0) cpu2 = 100.0;
        if (cpu3 > 100.0) cpu3 = 100.0;

        printf(
            "\n"
            "================= QNX MASTER =================\n"
            "CAN0 RX FPS                 : %.0f\n"
            "CAN1 RX FPS                 : %.0f\n"
            "Total TX FPS                : %.0f\n"
            "Estimated CAN load         : %.1f %%\n"
            "Safety min/avg/max         : %.3f / %.3f / %.3f ms\n"
            "Safety jitter              : %.3f ms\n"
            "Deadline misses >%.1f ms  : %llu\n"
            "Queues S/N/Noise/Error     : %u/%u/%u/%u\n"
            "Wrong predictions          : %llu\n"
            "Correct predictions        : %llu (latest only)\n"
            "Wrong records archived    : %llu\n"
            "Error overflow             : %llu\n"
            "CPU0 Safety+CAN0TX         : %.1f %%\n"
            "CPU1 CAN0RX                : %.1f %%\n"
            "CPU2 CAN1RX+Archive       : %.1f %%\n"
            "CPU3 CAN1TX+Diag+Noise    : %.1f %%\n"
            "Safety Node1 latch         : %s\n"
            "Safety Node2 latch         : %s\n"
            "================================================\n",

            rx0 == g_stats.last_rx_can0 &&
            rx1 == g_stats.last_rx_can1 ?
                0.0 :
                rx_fps,

            0.0,

            tx_fps,

            busload,

            safety_min ==
                UINT64_MAX ?
                0.0 :
                ns_to_ms(safety_min),

            avg_latency,

            safety_max == 0U ?
                0.0 :
                ns_to_ms(safety_max),

            jitter,

            SAFETY_DEADLINE_MS,

            (unsigned long long)
                deadline_misses,

            qs,
            qn,
            qnoise,
            qerror,

            (unsigned long long)
                wrong,

            (unsigned long long)
                correct,

            (unsigned long long)
                archived,

            (unsigned long long)
                overflow,

            cpu0,
            cpu1,
            cpu2,
            cpu3,

            g_safety_latched_node1 ?
                "ACTIVE" :
                "CLEAR",

            g_safety_latched_node2 ?
                "ACTIVE" :
                "CLEAR");

        /*
         * Dashboard telemetry.
         *
         * Note:
         * This JSON reports aggregate RX/TX metrics and queue state.
         * The dashboard remains outside the real-time safety path.
         */
        if (g_udp >= 0) {

            char json[1024];

            (void)snprintf(
                json,
                sizeof(json),

                "{"
                "\"can0_rx_fps\":%.0f,"
                "\"can1_rx_fps\":%.0f,"
                "\"tx_fps\":%.0f,"
                "\"busload\":%.1f,"
                "\"safety_latency_ms\":%.3f,"
                "\"safety_jitter_ms\":%.3f,"
                "\"deadline_misses\":%llu,"
                "\"q_safety\":%u,"
                "\"q_normal\":%u,"
                "\"q_noise\":%u,"
                "\"q_errors\":%u,"
                "\"wrong_predictions\":%llu,"
                "\"correct_predictions\":%llu,"
                "\"errors_archived\":%llu,"
                "\"error_overflow\":%llu,"
                "\"cpu0\":%.1f,"
                "\"cpu1\":%.1f,"
                "\"cpu2\":%.1f,"
                "\"cpu3\":%.1f"
                "}\n",

                rx_fps,
                0.0,
                tx_fps,
                busload,

                avg_latency,
                jitter,

                (unsigned long long)
                    deadline_misses,

                qs,
                qn,
                qnoise,
                qerror,

                (unsigned long long)
                    wrong,

                (unsigned long long)
                    correct,

                (unsigned long long)
                    archived,

                (unsigned long long)
                    overflow,

                cpu0,
                cpu1,
                cpu2,
                cpu3);

            (void)sendto(
                g_udp,
                json,
                strlen(json),
                0,
                (struct sockaddr *)&g_dashboard,
                sizeof(g_dashboard));
        }

        pthread_mutex_lock(
            &g_stats.lock);

        g_stats.last_rx_can0 =
            rx0;

        g_stats.last_rx_can1 =
            rx1;

        g_stats.last_tx_can0 =
            tx0;

        g_stats.last_tx_can1 =
            tx1;

        pthread_mutex_unlock(
            &g_stats.lock);

        last_wall_ns =
            wall_now;
    }

    return NULL;
}

/* ========================================================================== */
/* Architecture display                                                       */
/* ========================================================================== */

static void print_architecture(void)
{
    size_t safety_bytes =
        sizeof(g_q_safety.ring);

    size_t normal_bytes =
        sizeof(g_q_normal.ring);

    size_t noise_bytes =
        sizeof(g_q_noise.ring);

    size_t error_bytes =
        sizeof(g_q_error.ring);

    size_t corrected_bytes =
        sizeof(g_latest_corrected.slot);

    size_t total =
        safety_bytes +
        normal_bytes +
        noise_bytes +
        error_bytes +
        corrected_bytes;

    printf(
        "\n"
        "================ MEMORY / BUS ARCHITECTURE ================\n"
        "DATA BUS\n"
        "  NXP CAN payload                         : 8 bytes\n"
        "  Normal sensor value                     : uint16 / 100\n"
        "  IR                                      : byte0 obstacle\n"
        "\n"
        "ADDRESS BUS - logical software map\n"
        "  MCXA156 sensor bank                     : 0x1000\n"
        "  MCXA236 sensor bank                     : 0x2000\n"
        "  Safety queue                             : 0x0800\n"
        "  Wrong prediction history                : 0x4000\n"
        "  Latest corrected record                 : 0x5000\n"
        "\n"
        "MEMORY BUS\n"
        "  Safety fixed queue                      : %zu bytes\n"
        "  Normal fixed queue                      : %zu bytes\n"
        "  Noise fixed queue                       : %zu bytes\n"
        "  Error history                           : %zu bytes\n"
        "  Corrected double buffer                 : %zu bytes\n"
        "  Total fixed record storage              : %zu bytes\n"
        "\n"
        "RETENTION POLICY\n"
        "  WRONG prediction                        : historical\n"
        "  CORRECT prediction                      : latest only\n"
        "  Archive                                 : P5 / non-RT path\n"
        "\n"
        "QNX CORE / PRIORITY\n"
        "  CPU0 : Safety P60 + CAN0 TX P55\n"
        "  CPU1 : CAN0 RX P50\n"
        "  CPU2 : CAN1 RX P50 + Archive P5\n"
        "  CPU3 : CAN1 TX P55 + Diagnostics P15\n"
        "============================================================\n",

        safety_bytes,
        normal_bytes,
        noise_bytes,
        error_bytes,
        corrected_bytes,
        total);
}

/* ========================================================================== */
/* NXP command helper                                                         */
/* ========================================================================== */

static void send_start_stop(
    uint8_t node_id,
    uint8_t command)
{
    gateway_frame_t frame;

    memset(&frame,
           0,
           sizeof(frame));

    frame.can_id =
        (node_id == NODE1_ID) ?
            NODE1_CMD_ID :
            NODE2_CMD_ID;

    frame.dlc =
        8U;

    frame.data[0] =
        command;

    frame.source_bus =
        255U;

    frame.target_bus =
        (node_id == NODE1_ID) ?
            0U :
            1U;

    frame.node_id =
        node_id;

    frame.rx_timestamp_ns =
        monotonic_ns();

    if (safety_push(
            &frame)) {

        printf(
            "[MASTER] Node %u command 0x%02X queued on CAN%u\n",
            node_id,
            command,
            frame.target_bus);
    }
}

/* ========================================================================== */
/* Sensor-state display                                                       */
/* ========================================================================== */

static void print_sensor_state(void)
{
    unsigned i;

    printf(
        "\n================ SENSOR STATE ================\n");

    for (i = 0U;
         i < SENSOR_COUNT;
         ++i) {

        if (!g_latest_state[i].valid) {
            continue;
        }

        printf(
            "Node %u | %-18s | value=%8.3f | "
            "CAN=0x%03X | logical=0x%04X\n",

            g_latest_state[i].node_id,

            sensor_name(
                g_latest_state[i].sensor),

            g_latest_state[i].value,

            g_latest_state[i].can_id,

            g_latest_state[i].logical_addr);
    }

    printf(
        "================================================\n");
}

/* ========================================================================== */
/* RT thread creation                                                         */
/* ========================================================================== */

static int create_rt_thread(
    pthread_t *thread,
    void *(*entry)(void *),
    int priority,
    const char *name)
{
    pthread_attr_t attr;
    struct sched_param param;

    int rc;

    (void)pthread_attr_init(
        &attr);

    (void)pthread_attr_setinheritsched(
        &attr,
        PTHREAD_EXPLICIT_SCHED);

    (void)pthread_attr_setschedpolicy(
        &attr,
        SCHED_FIFO);

    memset(&param,
           0,
           sizeof(param));

    param.sched_priority =
        priority;

    (void)pthread_attr_setschedparam(
        &attr,
        &param);

    rc =
        pthread_create(
            thread,
            &attr,
            entry,
            NULL);

    (void)pthread_attr_destroy(
        &attr);

    if (rc != 0) {

        fprintf(stderr,
                "[-] thread %s P%d: %s\n",
                name,
                priority,
                strerror(rc));

        return rc;
    }

    printf(
        "[+] %-20s SCHED_FIFO P%d\n",
        name,
        priority);

    return 0;
}

/* ========================================================================== */
/* UDP                                                                        */
/* ========================================================================== */

static void init_udp(void)
{
    int broadcast = 1;

    g_udp =
        socket(
            AF_INET,
            SOCK_DGRAM,
            0);

    if (g_udp < 0) {
        return;
    }

    (void)setsockopt(
        g_udp,
        SOL_SOCKET,
        SO_BROADCAST,
        &broadcast,
        sizeof(broadcast));

    memset(
        &g_dashboard,
        0,
        sizeof(g_dashboard));

    g_dashboard.sin_family =
        AF_INET;

    g_dashboard.sin_port =
        htons(UDP_PORT);

    g_dashboard.sin_addr.s_addr =
        inet_addr(UDP_BROADCAST);
}

/* ========================================================================== */
/* Main                                                                       */
/* ========================================================================== */

int main(void)
{
    long cpu_result;

    cpu_result =
        sysconf(
            _SC_NPROCESSORS_ONLN);

    if (cpu_result > 0L) {
        g_cpu_count =
            (unsigned)cpu_result;
    }

    (void)signal(
        SIGINT,
        signal_handler);

    (void)signal(
        SIGTERM,
        signal_handler);

    printf(
        "============================================================\n"
        " QNX MASTER / MOMENTICS - DUAL NXP CAN GATEWAY\n"
        "============================================================\n"
        "CAN0 : FRDM-MCXA156 / Node 1\n"
        "CAN1 : FRDM-MCXA236 / Node 2\n"
        "CAN bitrate : %u bps\n"
        "Sensor cycle: %u ms\n"
        "CPUs        : %u\n"
        "============================================================\n",
        CAN_BITRATE,
        500U,
        g_cpu_count);

    init_storage();

    memset(
        &g_q_safety,
        0,
        sizeof(g_q_safety));

    memset(
        &g_q_normal,
        0,
        sizeof(g_q_normal));

    memset(
        &g_q_noise,
        0,
        sizeof(g_q_noise));

    memset(
        &g_q_error,
        0,
        sizeof(g_q_error));

    memset(
        &g_latest_corrected,
        0,
        sizeof(g_latest_corrected));

    init_pi_mutex(
        &g_q_safety.lock);

    init_pi_mutex(
        &g_q_normal.lock);

    init_pi_mutex(
        &g_q_noise.lock);

    init_pi_mutex(
        &g_q_error.lock);

    init_pi_mutex(
        &g_latest_corrected.lock);

    init_pi_mutex(
        &g_stats.lock);

    init_pi_mutex(
        &g_memory_bus_lock);

    memset(
        g_latest_state,
        0,
        sizeof(g_latest_state));

    memset(
        g_history_valid,
        0,
        sizeof(g_history_valid));

    g_stats.safety_latency_min_ns =
        UINT64_MAX;

    print_architecture();

    g_can0 =
        init_can(
            CAN0_DEV,
            "CAN0 / MCXA156");

    g_can1 =
        init_can(
            CAN1_DEV,
            "CAN1 / MCXA236");

    if (g_can0 < 0 ||
        g_can1 < 0) {

        fprintf(stderr,
                "[-] CAN initialization failed\n");

        if (g_can0 >= 0) {
            close(g_can0);
        }

        if (g_can1 >= 0) {
            close(g_can1);
        }

        return EXIT_FAILURE;
    }

    init_udp();

    /*
     * P60 Safety
     * P55 CAN TX
     * P50 CAN RX
     * P15 Diagnostics
     * P10 Noise
     * P5  Archive
     */
    if (create_rt_thread(
            &g_th_safety,
            safety_thread,
            60,
            "Safety") != 0) {

        return EXIT_FAILURE;
    }

    if (create_rt_thread(
            &g_th_tx0,
            can0_tx_thread,
            55,
            "CAN0 TX") != 0) {

        return EXIT_FAILURE;
    }

    if (create_rt_thread(
            &g_th_tx1,
            can1_tx_thread,
            55,
            "CAN1 TX") != 0) {

        return EXIT_FAILURE;
    }

    if (create_rt_thread(
            &g_th_rx0,
            can0_rx_thread,
            50,
            "CAN0 RX") != 0) {

        return EXIT_FAILURE;
    }

    if (create_rt_thread(
            &g_th_rx1,
            can1_rx_thread,
            50,
            "CAN1 RX") != 0) {

        return EXIT_FAILURE;
    }

    if (create_rt_thread(
            &g_th_diag,
            diagnostics_thread,
            15,
            "Diagnostics") != 0) {

        return EXIT_FAILURE;
    }

    if (create_rt_thread(
            &g_th_noise,
            noise_thread,
            10,
            "Congestion") != 0) {

        return EXIT_FAILURE;
    }

    if (create_rt_thread(
            &g_th_archive,
            archive_thread,
            5,
            "Error Archive") != 0) {

        return EXIT_FAILURE;
    }

    printf(
        "\n====================== MENU ======================\n"
        "1  START Node 1  -> 0x201 / D0=0x01\n"
        "2  STOP  Node 1  -> 0x201 / D0=0x00\n"
        "3  START Node 2  -> 0x202 / D0=0x01\n"
        "4  STOP  Node 2  -> 0x202 / D0=0x00\n"
        "5  Show decoded sensor readings\n"
        "6  Toggle CAN congestion/noise\n"
        "7  Clear safety latches\n"
        "8  Show memory / bus architecture\n"
        "9  Quit\n"
        "==================================================\n");

    while (g_running) {

        int c;

        printf(
            "\nSelect [1-9]: ");

        fflush(stdout);

        c = getchar();

        if (c == EOF) {
            break;
        }

        if (c == '\n') {
            continue;
        }

        switch (c) {

            case '1':

                send_start_stop(
                    NODE1_ID,
                    CMD_START);

                break;

            case '2':

                send_start_stop(
                    NODE1_ID,
                    CMD_STOP);

                break;

            case '3':

                send_start_stop(
                    NODE2_ID,
                    CMD_START);

                break;

            case '4':

                send_start_stop(
                    NODE2_ID,
                    CMD_STOP);

                break;

            case '5':

                print_sensor_state();

                break;

            case '6':

                g_congestion =
                    !g_congestion;

                printf(
                    "[MASTER] congestion/noise = %s\n",
                    g_congestion ?
                        "ON" :
                        "OFF");

                break;

            case '7':

                clear_safety_latches();

                break;

            case '8':

                print_architecture();

                break;

            case '9':

                g_running =
                    0;

                break;

            default:

                printf(
                    "[MASTER] invalid option\n");

                break;
        }

        while (c != '\n' &&
               c != EOF) {

            c = getchar();
        }
    }

    g_running =
        0;

    printf(
        "\n[MASTER] stopping...\n");

    (void)pthread_join(
        g_th_safety,
        NULL);

    (void)pthread_join(
        g_th_tx0,
        NULL);

    (void)pthread_join(
        g_th_tx1,
        NULL);

    (void)pthread_join(
        g_th_rx0,
        NULL);

    (void)pthread_join(
        g_th_rx1,
        NULL);

    (void)pthread_join(
        g_th_diag,
        NULL);

    (void)pthread_join(
        g_th_noise,
        NULL);

    (void)pthread_join(
        g_th_archive,
        NULL);

    if (g_can0 >= 0) {
        close(g_can0);
    }

    if (g_can1 >= 0) {
        close(g_can1);
    }

    if (g_udp >= 0) {
        close(g_udp);
    }

    printf(
        "[MASTER] stopped.\n"
        "Wrong prediction archive : "
        "/tmp/qnx_master/errors/archive/\n"
        "Latest corrected         : "
        "/tmp/qnx_master/corrected/latest_corrected.json\n");

    return EXIT_SUCCESS;
}
